name: CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install dependencies (Ubuntu)
      run: sudo apt-get update && sudo apt-get install -yq gm2
    - name: Set up CMake
      uses: lukka/get-cmake@latest
    - name: Configure with CMake
      run: cmake -S . -B build
    - name: Build with CMake
      run: cmake --build build
    - name: Run
      run: build/hello

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up MacPorts
      uses: melusina-org/setup-macports@v1
      with:
        parameters: 'macos.yaml'
    - name: Set up CMake
      uses: lukka/get-cmake@latest
    - name: Configure with CMake
      run: cmake -S . -B build
    - name: Build with CMake
      run: cmake --build build
    - name: Run
      run: build/hello
