name: CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -yq gm2

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install gcc

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build

    - name: Run
      run: build/hello
